//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXamlAnalysisReference.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFXamlAnalysisReference.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example localized text for button.
        /// </summary>
        public static string ExampleButtonText {
            get {
                return ResourceManager.GetString("ExampleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example localized content.
        /// </summary>
        public static string ExampleContentLabel {
            get {
                return ResourceManager.GetString("ExampleContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder from resournce file.
        /// </summary>
        public static string ExampleEntryCellPlaceholder {
            get {
                return ResourceManager.GetString("ExampleEntryCellPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text from resource file.
        /// </summary>
        public static string ExampleEntryCellText {
            get {
                return ResourceManager.GetString("ExampleEntryCellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A placeholder from resources.
        /// </summary>
        public static string ExampleEntryPlaceholder {
            get {
                return ResourceManager.GetString("ExampleEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some entry text from a resource.
        /// </summary>
        public static string ExampleEntryText {
            get {
                return ResourceManager.GetString("ExampleEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a resource based picker title.
        /// </summary>
        public static string ExamplePickerTitle {
            get {
                return ResourceManager.GetString("ExamplePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this placeholder is from a resource.
        /// </summary>
        public static string ExampleSearchbarPlaceholder {
            get {
                return ResourceManager.GetString("ExampleSearchbarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text for switchcell from resource.
        /// </summary>
        public static string ExampleSwitchCellText {
            get {
                return ResourceManager.GetString("ExampleSwitchCellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a resource based title.
        /// </summary>
        public static string ExampleTableSectionTitle {
            get {
                return ResourceManager.GetString("ExampleTableSectionTitle", resourceCulture);
            }
        }
    }
}
